In [2]:
import pandas as pd

# Carregar dataset

df = pd.read_csv('/Copy of WaterQuality.csv')

# Verificar a quantidade de nulos por coluna
print ("Valores ausentes por coluna:")
print(df.isnull().sum())

Valores ausentes por coluna:
Station_ID          0
Station_Location    0
Date                0
pH                  1
Dissolved_Oxygen    0
Turbidity           0
Nitrogen            0
Phosphorus          0
Rainfall            0
Land_Use            1
Pollution_Event     0
Fish_Population     0
dtype: int64

In [5]:
df['pH'] = df['pH'].fillna(df['pH'].median())

In [6]:
df['Land_Use'] = df['Land_Use'].fillna('Unknown')

In [8]:
df.head()

,Station_ID,Station_Location,Date,pH,Dissolved_Oxygen,Turbidity,Nitrogen,Phosphorus,Rainfall,Land_Use,Pollution_Event,Fish_Population
0,1,"50.7959,47.7005",2025-01-01,7.3,9.4,9.7,2.5,0.66,9.6,Urban,1,59
1,2,"42.2562,112.3186",2025-01-02,6.5,8.5,8.2,5.4,0.28,7.5,Forest,1,162
2,3,"65.1943,3.7017",2025-01-03,7.2,6.6,12.4,2.2,0.54,28.0,Agricultural,1,78
3,4,"38.9249,-150.5911",2025-01-04,7.7,7.4,11.5,3.1,1.32,5.8,Forest,0,157
4,5,"69.3857,34.3640",2025-01-05,7.9,9.2,10.5,4.8,0.86,17.3,Agricultural,0,111

In [10]:
# Separar Latitude e Longitude usando str.split
df[['Latitude','Longitude']] = df['Station_Location'].str.split(',',expand=True)

# Deletando a coluna antiga
df = df.drop(columns=['Station_Location'])

# Visualizar
df.head()

,Station_ID,Date,pH,Dissolved_Oxygen,Turbidity,Nitrogen,Phosphorus,Rainfall,Land_Use,Pollution_Event,Fish_Population,Latitude,Longitude
0,1,2025-01-01,7.3,9.4,9.7,2.5,0.66,9.6,Urban,1,59,50.7959,47.7005
1,2,2025-01-02,6.5,8.5,8.2,5.4,0.28,7.5,Forest,1,162,42.2562,112.3186
2,3,2025-01-03,7.2,6.6,12.4,2.2,0.54,28.0,Agricultural,1,78,65.1943,3.7017
3,4,2025-01-04,7.7,7.4,11.5,3.1,1.32,5.8,Forest,0,157,38.9249,-150.5911
4,5,2025-01-05,7.9,9.2,10.5,4.8,0.86,17.3,Agricultural,0,111,69.3857,34.3640

In [11]:
print(df.dtypes)

Station_ID            int64
Date                 object
pH                  float64
Dissolved_Oxygen    float64
Turbidity           float64
Nitrogen            float64
Phosphorus          float64
Rainfall            float64
Land_Use             object
Pollution_Event       int64
Fish_Population       int64
Latitude             object
Longitude            object
dtype: object

In [13]:
# Convertendo Lati e Long para Float
df['Latitude'] = df['Latitude'].astype(float)
df['Longitude'] = df['Longitude'].astype(float)

# Convertendo Date para Datetime
df['Date'] = pd.to_datetime(df['Date'])

# Convertendo Land_Use para String
df['Land_Use'] = df['Land_Use'].astype("string")

# Convertendo Polution_Event para boolean
df['Pollution_Event'] = df['Pollution_Event'].astype(bool)

In [14]:
# Arrumando a Ordem da Colunas
nova_ordem = [
    'Station_ID',
    'Latitude',
    'Longitude',
    'Date',
    'pH',
    'Dissolved_Oxygen',
    'Turbidity',
    'Nitrogen',
    'Phosphorus',
    'Rainfall',
    'Pollution_Event',
    'Fish_Population',
    'Land_Use'
]

# Aplicando nova ordem ao dataframe
df = df[nova_ordem]

df.head()

,Station_ID,Latitude,Longitude,Date,pH,Dissolved_Oxygen,Turbidity,Nitrogen,Phosphorus,Rainfall,Pollution_Event,Fish_Population,Land_Use
0,1,50.7959,47.7005,2025-01-01,7.3,9.4,9.7,2.5,0.66,9.6,True,59,Urban
1,2,42.2562,112.3186,2025-01-02,6.5,8.5,8.2,5.4,0.28,7.5,True,162,Forest
2,3,65.1943,3.7017,2025-01-03,7.2,6.6,12.4,2.2,0.54,28.0,True,78,Agricultural
3,4,38.9249,-150.5911,2025-01-04,7.7,7.4,11.5,3.1,1.32,5.8,False,157,Forest
4,5,69.3857,34.3640,2025-01-05,7.9,9.2,10.5,4.8,0.86,17.3,False,111,Agricultural

In [15]:
# Exportando resultado

df.to_csv('WaterQuality_Clean.csv',index=False)